server:
  port: 10000

spring:
  profiles:
    active:
      - master
  batch:
    job:
      enabled: false
    initialize-schema: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch?allowPublicKeyRetrieval=true&useSSL=false&charset=utf8
    username: jamie
    password: Hsbc1234
    initialization-mode: always
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 5
      idle-timeout: 30000
      minimum-idle: 2
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  rabbit:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connRecvThreads: 5
    channelCacheSize: 10
    virtual-host: /
batch:
  scheduling:
    enabled: true
  partitioner:
    partition: 1 # partition count, grid size
  job:
    name: importUserDataTest
    chunk.size: 20
    input:
      path: c:/temp/source
      filter: '.csv'
    ouput:
      path: c:/temp/target
    failure:
      path: c:/temp/failure
    scheduler:
      cron: 0 */1 * * * ? #[s] [m] [h] [d] [m] [w] [y]
